import net from "node:net";
import readline from "node:readline";

const transitions = new Set(["starting:navigating","navigating:observing","observing:waiting_for_model","waiting_for_model:acting","acting:verifying","verifying:settling","settling:finished","verifying:observing","acting:observing","observing:acting","navigating:finished","observing:finished","waiting_for_model:finished","acting:finished","verifying:finished"]);

export class BaeldAgent {
  constructor(socket, lines, sessionId, metadata) { this.socket=socket; this.lines=lines; this.sessionId=sessionId; this.metadata=metadata; this.generation=0; this.previous=null; this.pending=new Map(); lines.on("line", line=>this.#acknowledge(line)); socket.on("error", error=>this.#rejectAll(error)); socket.on("close", ()=>this.#rejectAll(new Error("Baeld phase socket closed"))); }
  static async connect(options={}) { const socketPath=options.socketPath??process.env.BAELD_PHASE_SOCKET; const sessionId=options.sessionId??process.env.BAELD_SESSION_ID; if(!socketPath||!sessionId) throw new Error("Run through `baeld run` or provide socketPath and sessionId"); const socket=net.createConnection(socketPath); await new Promise((resolve,reject)=>{socket.once("connect",resolve);socket.once("error",reject)}); return new BaeldAgent(socket,readline.createInterface({input:socket,crlfDelay:Infinity}),sessionId,{framework:options.framework,workload:options.workload,browserVersion:options.browserVersion}); }
  async phase(name,options={}) { if(this.previous===null&&name!=="starting") throw new Error("The first phase must be starting"); if(this.previous!==null&&!transitions.has(`${this.previous}:${name}`)) throw new Error(`Invalid phase transition ${this.previous} -> ${name}`); const generation=++this.generation; const request={schema_version:1,session_id:this.sessionId,generation,phase:name,expected_wait_ms:options.expectedWaitMs??null,framework:this.metadata.framework??null,workload:this.metadata.workload??null,browser_version:this.metadata.browserVersion??null,critical_live_connection:options.criticalLiveConnection??false}; const ack=await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{this.pending.delete(generation);reject(new Error(`Baeld phase ${name} timed out`))},options.timeoutMs??15000);this.pending.set(generation,{resolve,reject,timeout});this.socket.write(`${JSON.stringify(request)}\n`)}); this.previous=name; return ack; }
  waitingForModel(expectedWaitMs,options={}) { return this.phase("waiting_for_model",{...options,expectedWaitMs}); }
  acting(options) { return this.phase("acting",options); } verify(options) { return this.phase("verifying",options); } finish(options) { return this.phase("finished",options); }
  session() { return {id:this.sessionId,cdpUrl:process.env.BAELD_CDP_URL,filterProfile:process.env.BAELD_FILTER_PROFILE,mode:process.env.BAELD_SESSION_MODE}; }
  close() { this.#rejectAll(new Error("Baeld adapter closed"));this.lines.close();this.socket.destroy(); }
  #acknowledge(line) { let ack;try{ack=JSON.parse(line)}catch(error){this.#rejectAll(new Error(`Invalid Baeld acknowledgement: ${error}`));return}const waiter=this.pending.get(ack.generation);if(!waiter)return;this.pending.delete(ack.generation);clearTimeout(waiter.timeout);ack.accepted?waiter.resolve(ack):waiter.reject(new Error(ack.error??"Phase rejected")); }
  #rejectAll(error) { for(const waiter of this.pending.values()){clearTimeout(waiter.timeout);waiter.reject(error)}this.pending.clear(); }
}

export async function connectPlaywright(playwright,options={}) { const cdpUrl=options.cdpUrl??process.env.BAELD_CDP_URL;if(!cdpUrl)throw new Error("BAELD_CDP_URL is not set");const browser=await playwright.chromium.connectOverCDP(cdpUrl);return {browser,agent:await BaeldAgent.connect({...options,framework:"playwright"})}; }
export async function connectStagehand({Stagehand,localBrowser},options={}) { const cdpUrl=options.cdpUrl??process.env.BAELD_CDP_URL;if(!cdpUrl)throw new Error("BAELD_CDP_URL is not set");const browser=await localBrowser.connect({cdpUrl});const stagehand=await Stagehand.create({...(options.stagehandOptions??{}),browser,logging:options.logging??{level:"off",format:"json"}});return {stagehand,browser,agent:await BaeldAgent.connect({...options,framework:"stagehand"})}; }
export async function installFiltering(page,profile=process.env.BAELD_FILTER_PROFILE??"safe") { const blocked=profile==="text"?new Set(["image","media","font"]):profile==="balanced"?new Set(["media"]):new Set();const tracker=/(?:doubleclick|google-analytics|googletagmanager|segment\.io|hotjar)\./i;if(blocked.size===0&&!['balanced','text'].includes(profile))return;await page.route("**/*",route=>{const request=route.request();if(blocked.has(request.resourceType())||(['balanced','text'].includes(profile)&&tracker.test(request.url())))return route.abort("blockedbyclient");return route.continue()});if(['balanced','text'].includes(profile))await page.addStyleTag({content:"*,*::before,*::after{animation-duration:0s!important;transition-duration:0s!important}"}).catch(()=>{}); }
export async function withModelWait(agent,expectedWaitMs,operation,options={}) { await agent.waitingForModel(expectedWaitMs,options);try{return await operation()}finally{await agent.acting()} }
